project:
  type: website

website:
  navbar:
    logo:
      image: "teevial.jpg"
      href: "https://teevial.com"
    left:
      - href: index.qmd
        text: Ներածություն
      - href: demographics.qmd
        text: Ժողովրդագրություն
      - href: waterhome.qmd
        text: Ջուրը տանը
      - href: waternature.qmd
        text: Ջուրը բնության մեջ
      - href: interests.qmd
        text: Հետաքրքրություններ

format:
  html:
    theme: cosmo
    css:
      - fonts.css
      - styles.css
    toc: false
