project:
  type: website

website:
  navbar:
    title: false                     # Optional: hides default Quarto title
    logo: teevial.jpg               # ✅ Logo image file
    logo-href: https://teevial.com  # ✅ External link for logo
    left:
      - href: index.qmd
        text: Ներածություն
      - href: demographics.qmd
        text: Ժողովրդագրություն
      - href: waterhome.qmd
        text: Ջուրը տանը
      - href: waternature.qmd
        text: Ջուրը բնության մեջ
      - href: interests.qmd
        text: Հետաքրքրություններ

format:
  html:
    theme: 
      - cosmo
      - fonts.css             # ✅ Custom fonts
    css: styles.css
    toc: false
