project:
  type: website

website:
  navbar:
    logo: "teevial.jpg"        # just the image path as a string
    logo-href: "https://teevial.com"  # link for the logo
    left:
      - href: index.qmd
        text: Ներածություն
      - href: demographics.qmd
        text: Ժողովրդագրություն
      - href: waterhome.qmd
        text: Ջուրը տանը
      - href: waternature.qmd
        text: Ջուրը բնության մեջ
      - href: interests.qmd
        text: Հետաքրքրություններ

format:
  html:
    theme: cosmo
    css:
      - fonts.css
      - styles.css
    toc: false
